### ISSUE TITLE
Not compatible with php 7 anymore

### ISSUE THREAD

**Issue by ametad** [PHPExpertsInc/SimpleDTO#23]
From versions 2.7 and 3.0 (which point both to the same commit) this package is not compatible with PHP version 7 anymore. Because of the use of ReflectionProperty::hasDefaultValue() [here](https://github.com/PHPExpertsInc/SimpleDTO/blob/03b55154d8d46fcd628b2b706bb5f9957e62df9e/src/SimpleDTO.php#L121).

The PHP documentation points out that the function is available from PHP version 8:
https://www.php.net/manual/en/reflectionproperty.hasdefaultvalue.php 

Perhaps it is a good idea to:

- remove version 2.7 in this package (2.6 is compatible with PHP 7);
- add a constraint in composer.json of `"php": ">=8.0"` for version 3.0 of this package;

**Comment by hopeseekr** [comment]
I have a legit question....

The project has over 97% unit test code coverage, including this line in question and I test it via PHP 7.4 through 8.3 (see [test.sh](test.sh)). 

I wonder why it isn't blowing up in the unit tests???

**Comment by hopeseekr** [comment]
OK I figured it out...

The Travis CI alternative (test.sh) was created on 2023-07-20, at which point, I myself encountered this bug.

It was fixed in b0a30b7c (Theodore R. Smith at 2023-07-21 04:58:04 CDT.

**Comment by hopeseekr** [comment]
Fixed in [Version 3.5.0](https://github.com/PHPExpertsInc/SimpleDTO/releases/tag/v3.5.0).
